services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false  # Deshabilitar seguridad si no se necesita
      - http.host=0.0.0.0              # Aceptar conexiones desde cualquier IP
    ports:
      - "9200:9200"
    networks:
      - elasticsearch_net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.1
    container_name: logstash
    user: "root"
    ports:
      - "8443:8443"
      - "9990:9990"
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./pipeline/:/usr/share/logstash/pipeline/
      - /var/log:/var/log:ro
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
    networks:
      - elasticsearch_net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.1
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elasticsearch_net

networks:
  elasticsearch_net:
    driver: bridge
