global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Product Service
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Invoice Service
  - job_name: 'invoice-service'
    static_configs:
      - targets: ['invoice-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Chat Service
  - job_name: 'chat-service'
    static_configs:
      - targets: ['chat-service:3004']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Frontend
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # PostgreSQL Databases
  - job_name: 'postgres-auth'
    static_configs:
      - targets: ['auth-db:5432']
    scrape_interval: 60s

  - job_name: 'postgres-product'
    static_configs:
      - targets: ['product-db:5432']
    scrape_interval: 60s

  - job_name: 'postgres-invoice'
    static_configs:
      - targets: ['invoice-db:5432']
    scrape_interval: 60s

  - job_name: 'postgres-chat'
    static_configs:
      - targets: ['chat-db:5432']
    scrape_interval: 60s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
